---
# We only check for the directory's existance as on Compose, it may be
# owned by root, and we won't have the authority to chown. On k8s, this
# should be accomplished by the container build scripts.
- name: Ensure vhost directories exist
  file:
    path: "{{ item.docroot }}"
    state: directory
  loop: "{{ flightdeck_web.vhosts | default(flightdeck_web_default_vhosts) }}"
  when:
    - item.docroot is defined
- name: Configure apache vhosts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "apache"
    group: "apache"
    mode: "u=rw,g=r,o="
  loop:
    - src: "templates/httpd.conf"
      dest: "/etc/apache2/httpd.conf"
    - src: "templates/000_default.conf"
      dest: "/etc/apache2/sites.d/000_default.conf"
- name: Configure php
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "apache"
    group: "apache"
    mode: "u=rw,g=r,o="
  loop:
    - src: "templates/php.ini"
      dest: "/etc/php81/php.ini"
    - src: "templates/00_opcache.ini"
      dest: "/etc/php81/conf.d/00_opcache.ini"
    - src: "templates/apcu.ini"
      dest: "/etc/php81/conf.d/apcu.ini"
- name: Configure xdebug
  template:
    src: "templates/50_xdebug.ini"
    dest: "/etc/php81/conf.d/50_xdebug.ini"
    owner: "apache"
    group: "apache"
    mode: "u=rw,g=r,o="
- name: Update initial directory
  lineinfile:
    path: "/var/www/.bashrc"
    line: "cd {{ flightdeck_web.initialDir | default('$HOME') }}"
